configMapGenerator:
  - name: istio-services-grafana-dashboards
    files:
      - dashboards/istio-extension-dashboard.json
      - dashboards/istio-mesh-dashboard.json
      - dashboards/istio-performance-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: istio-grafana-dashboards
    files:
      - dashboards/istio_loki.json
      - dashboards/istio_control_plane.json
      - dashboards/opentelemetry-apm.json
      - istio-service-monitor.yaml
    options:
      labels:
        grafana_dashboard: "1"

resources:
  - virtual-service.yaml