configMapGenerator:
  - name: grafana-dashboards-set1
    files:
      - dashboards/istio_control_plane.json
      - dashboards/fastapi-observability.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboards-set2
    files:
      - dashboards/istio_loki.json
    options:
      labels:
        grafana_dashboard: "1"

resources:
  - virtual-service.yaml