grafana:
  adminPassword: admin
  sidecar:
    datasources:
      name: Mimir
      uid: mimir
      url: http://mimir-nginx.monitoring.svc.cluster.local/prometheus
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      # Allow discovery in all namespaces for dashboards
      searchNamespace: ALL

  additionalDataSources:
   - name: Loki
     uid: loki
     access: proxy
#     basicAuth: true
#     secureJsonData:
#         basicAuthPassword: pass
#     basicAuthUser: daco
     editable: false
     jsonData:
         tlsSkipVerify: true
     orgId: 1
     type: loki
     url: http://loki.logging.svc.cluster.local:3100
     version: 1
   - name: Prometheus
     uid: prometheus
     editable: false
     jsonData:
         tlsSkipVerify: true
     orgId: 1
     type: loki
     url: http://kube-prometheus-stack-prometheus.monitoring:9090
     version: 1

remote_write:
  - url: http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push
    remote_timeout: 30s