grafana:
  adminPassword: admin
  sidecar:
    datasources:
      name: Mimir
      uid: mimir
      url: http://mimir-nginx.monitoring.svc.cluster.local/prometheus
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      # Allow discovery in all namespaces for dashboards
      searchNamespace: ALL

  additionalDataSources:
    - uid: prometheus
      orgId: 1
      name: Prometheus
      type: prometheus
      typeName: Prometheus
      access: proxy
      url: http://kube-prometheus-stack-prometheus.monitoring:9090
      password: ''
      user: ''
      database: ''
      basicAuth: false
      isDefault: false
      jsonData:
        exemplarTraceIdDestinations:
          - datasourceUid: tempo
            name: TraceID
        httpMethod: POST
      readOnly: false
      editable: true
    - uid: tempo
      orgId: 1
      name: Tempo
      type: tempo
      typeName: Tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3100
      password: ''
      user: ''
      database: ''
      basicAuth: false
      isDefault: false
      jsonData:
        nodeGraph:
          enabled: true
        tracesToLogsV2:
          customQuery: false
          datasourceUid: loki
          filterBySpanID: false
          filterByTraceID: true
          tags:
            - key: service.name
              value: compose_service
      readOnly: false
      editable: true
    - uid: loki
      orgId: 1
      name: Loki
      type: loki
      typeName: Loki
      access: proxy
      url: http://loki-gateway.logging.svc.cluster.local
      password: ''
      user: ''
      database: ''
      basicAuth: false
      isDefault: false
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: (?:trace_id)=(\w+)
            matcherType: regex
            name: TraceID
            url: $${__value.raw}
      readOnly: false
      editable: true

prometheus:
  prometheusSpec:
    ruleNamespaceSelector:
      matchLabels:
        monitoring: enabled
    serviceMonitorNamespaceSelector:
      matchLabels:
        monitoring: enabled
    podMonitorNamespaceSelector:
      matchLabels:
        monitoring: enabled
    remoteWriteDashboards: true
    remoteWrite:
      - name: mimir
        url: http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push
        remoteTimeout: 30s
        headers:
          X-Scope-OrgID: in-cluster