grafana:
  adminPassword: admin
  sidecar:
    datasources:
      name: Mimir
      uid: mimir
      url: http://mimir-nginx.monitoring.svc.cluster.local/prometheus
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      # Allow discovery in all namespaces for dashboards
      searchNamespace: ALL

  additionalDataSources:
   - name: Loki
     uid: loki
     access: proxy
#     basicAuth: true
#     secureJsonData:
#         basicAuthPassword: pass
#     basicAuthUser: daco
     editable: false
     jsonData:
         tlsSkipVerify: true
     orgId: 1
     type: loki
     url: http://loki-gateway.logging.svc.cluster.local
     version: 1
   - name: Prometheus
     uid: prometheus
     editable: false
     jsonData:
         tlsSkipVerify: true
     orgId: 1
     type: prometheus
     url: http://kube-prometheus-stack-prometheus.monitoring:9090
     version: 1

prometheus:
  prometheusSpec:
    remoteWriteDashboards: true
    remoteWrite:
      - name: mimir
        url: http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push
        remoteTimeout: 30s
        headers:
          X-Scope-OrgID: in-cluster
