apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:latest
  ports:
    - name: otlp-grpc
      port: 4317
    - name: otlp-http
      port: 4318
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch: null
    exporters:
      # Send logs (and optionally traces/metrics) to Loki's OTLP endpoint
      otlphttp/loki:
        endpoint: http://loki-gateway.logging.svc.cluster.local/otlp

      otlphttp/tempo:
        endpoint: http://tempo.monitoring.svc.cluster.local:4318

    service:
      pipelines:
        logs:
          receivers: 
            - otlp
          processors: 
            - batch
          exporters: 
            - otlphttp/loki
        traces:
          receivers: 
            - otlp
          processors: 
            - batch
          exporters: 
            - otlphttp/tempo
