apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:latest
  ports:
    - name: otlp-grpc
      port: 4317
    - name: otlp-http
      port: 4318
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: "kubernetes"
              kubernetes_sd_configs:
                - role: pod
      filelog:
        include: ["/var/log/pods/*.log"]
    processors:
      batch:
        timeout: 5s
    exporters:
      loki:
        endpoint: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
      otlphttp/tempo:
        endpoint: http://tempo.monitoring.svc.cluster.local:4318
      debug:

    service:
      pipelines:
        logs:
          receivers: 
            - otlp
            - filelog
          processors: 
            - batch
          exporters: 
            - loki
            - debug
        traces:
          receivers: 
            - otlp
          processors: 
            - batch
          exporters: 
            - otlphttp/tempo
            - debug
