apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
      attributes:
        actions:
          - key: "environment"
            value: "development"
            action: insert
          - key: "from"
            value: "open-telemetry"
            action: insert
    exporters:
      otlphttp/metrics:
        endpoint: http://mimir-nginx.monitoring.svc.cluster.local/otlp
      otlphttp/loki:
        endpoint: http://loki.logging.svc.cluster.local:3100/otlp
      otlphttp/tempo:
        endpoint: http://tempo.monitoring.svc.cluster.local:4318
      debug: {}

    connectors:
      spanmetrics:
        dimensions:
          - name: http.method
          - name: http.status_code
          - name: http.route

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, memory_limiter, attributes]
          exporters: [otlphttp/tempo, debug, spanmetrics]
        metrics:
          receivers: [spanmetrics]
          processors: [batch]
          exporters: [debug, otlphttp/metrics]
        logs:
          receivers: [otlp]
          processors: [batch, attributes]
          exporters: [otlphttp/loki, debug]
