apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2025-04-25T12:46:59+07:00"
    prometheus.io/port: "15014"
    prometheus.io/scrape: "true"
    sidecar.istio.io/inject: "false"
  labels:
    app: istiod
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.25.1
    helm.sh/chart: istiod-1.25.1
    install.operator.istio.io/owning-resource: unknown
    istio: pilot
    istio.io/dataplane-mode: none
    istio.io/rev: default
    operator.istio.io/component: Pilot
    pod-template-hash: 648cbbf45c
    sidecar.istio.io/inject: "false"
  name: istiod-648cbbf45c-pkzh7
  namespace: istio-system
spec:
  containers:
  - args:
    - discovery
    - --monitoringAddr=:15014
    - --log_output_level=default:info
    - --domain
    - cluster.local
    - --keepaliveMaxServerConnectionAge
    - 30m
    env:
    - name: REVISION
      value: default
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
    - name: KUBECONFIG
      value: /var/run/secrets/remote/config
    - name: CA_TRUSTED_NODE_ACCOUNTS
      value: istio-system/ztunnel
    - name: PILOT_TRACE_SAMPLING
      value: "1"
    - name: PILOT_ENABLE_ANALYSIS
      value: "false"
    - name: CLUSTER_ID
      value: cluster-1
    - name: GOMEMLIMIT
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
    - name: GOMAXPROCS
      valueFrom:
        resourceFieldRef:
          divisor: "1"
          resource: limits.cpu
    - name: PLATFORM
    image: docker.io/istio/pilot:1.25.1
    name: discovery
    ports:
    - containerPort: 8080
      name: http-debug
    - containerPort: 15010
      name: grpc-xds
    - containerPort: 15012
      name: tls-xds
    - containerPort: 15017
      name: https-webhooks
    - containerPort: 15014
      name: http-monitoring
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 1
      periodSeconds: 3
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: istio-token
      readOnly: true
    - mountPath: /var/run/secrets/istio-dns
      name: local-certs
    - mountPath: /etc/cacerts
      name: cacerts
      readOnly: true
    - mountPath: /var/run/secrets/remote
      name: istio-kubeconfig
      readOnly: true
    - mountPath: /var/run/secrets/istiod/tls
      name: istio-csr-dns-cert
      readOnly: true
    - mountPath: /var/run/secrets/istiod/ca
      name: istio-csr-ca-configmap
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lpn2b
      readOnly: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  serviceAccountName: istiod
  tolerations:
  - key: cni.istio.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
    name: local-certs
  - name: istio-token
    projected:
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - name: cacerts
    secret:
      optional: true
      secretName: cacerts
  - name: istio-kubeconfig
    secret:
      optional: true
      secretName: istio-kubeconfig
  - name: istio-csr-dns-cert
    secret:
      optional: true
      secretName: istiod-tls
  - configMap:
      name: istio-ca-root-cert
      optional: true
    name: istio-csr-ca-configmap
  - name: kube-api-access-lpn2b
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.namespace
            path: namespace
