global:
  dnsNamespace: kube-system
  clusterDomain: cluster.local

serviceAccount:
  create: create
  # -- Alertmanager specific service account name. If not set and create is set to true, the default
  # name will be the default mimir service account's name with the "-alertmanager" suffix.
  name: "mimir-sa"

disableComponents: &disableComponents
  enabled: false

mimir:
  structuredConfig:
    usage_stats:
      enabled: false
      installation_mode: helm
    blocks_storage:
      backend: s3
      bucket_store:
        sync_dir: /data/tsdb-sync
      s3:
        bucket_name: my-mimir-bucket-199907060500
        endpoint: s3.us-east-1.amazonaws.com
        insecure: false
      tsdb:
        dir: /data/tsdb
    compactor:
      data_dir: /data
    multitenancy_enabled: false
    frontend:
      log_queries_longer_than: 10s
    ingester:
      instance_limits:
        max_ingestion_rate: 0
      ring:
        final_sleep: 0s
        num_tokens: 512
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    server:
      log_level: debug
      grpc_server_max_concurrent_streams: 1000
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
    limits:
      ingestion_rate: 80000
      max_global_series_per_metric: 0
      max_global_series_per_user: 0
      max_label_names_per_series: 40
    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: false
    runtime_config:
      file: /var/{{ include "mimir.name" . }}/runtime.yaml
minio:
  <<: *disableComponents
querier:
  replicas: 2
alertmanager:
  <<: *disableComponents
ruler:
  <<: *disableComponents
ingester:
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    enabled: true
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    storageClass: gp2
store_gateway:
  persistentVolume:
    storageClass: gp2
  zoneAwareReplication:
    enabled: false

compactor:
  persistentVolume:
    storageClass: gp2