apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cross-network-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: eastwestgateway
  servers:
    - port:
        number: 15443
        name: tls
        protocol: TLS
      tls:
        mode: AUTO_PASSTHROUGH
      hosts:
        - "*.local"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld-eastwest
  namespace: istio-system
spec:
  hosts:
  - "helloworld.sample.svc.cluster.local"  # 👈 this is the critical part: full FQDN SNI
  gateways:
  - cross-network-gateway       # 👈 your east-west Gateway name
  tls:
  - match:
    - gateways:
      - cross-network-gateway
      port: 15443
      sniHosts:
      - "helloworld.sample.svc.cluster.local"  # 👈 match SNI during TLS handshake
    route:
    - destination:
        host: helloworld.sample.svc.cluster.local
        port:
          number: 5000                          # 👈 the internal service port (example)
