kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: app-b-httpscaledobject
spec:
  hosts:
  - "istio-gateway-lb-fc39df2a05fb0745.elb.us-east-1.amazonaws.com"
  pathPrefixes:
  - "/"
  scaleTargetRef:
    name: app-b
    kind: Deployment
    apiVersion: apps/v1
    service: app-b
    port: 8000
  replicas:
    min: 1
    max: 10
  scalingMetric:
    requestRate:
      granularity: 1s
      targetValue: 1  # Low value for easy triggering during tests (e.g., ~60 requests over 1 minute to hit 1 RPS average)
      window: 5s