apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: app-b-keda-http-addon-vs
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/shared-gateway
  http:
  - match:
    - port: 8080
      uri:
        prefix: /app-b-keda/
    - port: 8080
      uri:
        prefix: /app-b-keda
    rewrite:
      uri: /
    route:
    - destination:
        host: app-b.test-app.svc.cluster.local
        port:
          number: 8000