apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl-test-app
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: curl
              image: curlimages/curl:latest
              args:
                - /bin/sh
                - -c
                - |
                  for service in app-a app-b app-c; do
                    for path in / /io_task /chain /error_test; do
                      curl -s -o /dev/null -w "%{http_code} $service$path\n" http://$service:8000$path;
                    done
                  done