apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: app
        image: ghcr.io/blueswen/fastapi-observability/app:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
          - name: OTLP_GRPC_ENDPOINT
            value:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://opentelemetry-collector.opentelemetry-operator-system.svc.cluster.local:4317
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"
          - name: OTEL_TRACES_EXPORTER
            value: otlp
          - name: OTEL_METRICS_EXPORTER
            value: otlp
          - name: OTEL_LOGS_EXPORTER
            value: otlp