apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base directory
resources:
  - deploy.yaml
  - service.yaml
  - virtual-service.yaml
  - ../test-app-common/false-vs.yaml
#  - service-monitor.yaml