apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-app
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      purpose: testing
  endpoints:
    - port: http-monitoring
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - test-app
