apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: test-app
  labels:
    app: test-app
spec:
  selector:
    app: app-a
  ports:
    - port: 80
      targetPort: 8000
      name: metrics
