apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-app-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      purpose: test
  endpoints:
    - port: metrics        # The port name from your Service
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - test-app
