apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
      annotations:
        instrumentation.opentelemetry.io/inject-python: "opentelemetry-operator-system/test-app-instrumentation"
    spec:
      containers:
      - name: app
        image: ghcr.io/blueswen/opentelemetry-apm/fastapi:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        command:
          - uv
          - run
          - python
          - main.py
        env:
          - name: OTEL_SERVICE_NAME
            value: test-app
          - name: TARGET_ONE_SVC
            value: app-a:8000
          - name: TARGET_TWO_SVC
            value: app-a:8000