mimir:
  common:
    storage:
      backend: s3
      s3:
        endpoint: s3.amazonaws.com
        bucket_name: my-mimir-bucket
        region: us-east-1

alertmanager:
  enabled: false

serviceAccount:
  create: false
  name: mimir-sa