apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/henrypham67/istio
      targetRevision: HEAD
      path: observability/argo/values/grafana
      ref: custom
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 9.4.4
      helm:
        valueFiles:
          - $custom/observability/argo/values/grafana/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
