apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/henrypham67/istio
      targetRevision: HEAD
      ref: custom
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: 2.17.1
      helm:
        valueFiles:
          - $custom/observability/argo/values/keda.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
