apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-telemetry
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-operator
      targetRevision: 0.90.4
    - repoURL: https://github.com/henrypham67/istio
      targetRevision: HEAD
      path: observability/argo/values/open-telemetry
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
