apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickwit
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/henrypham67/istio
      targetRevision: HEAD
      ref: custom
    - repoURL: https://helm.quickwit.io
      chart: quickwit
      targetRevision: 0.7.18
      helm:
        valueFiles:
          - $custom/observability/argo/values/quickwit.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
