apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/henrypham67/istio
      targetRevision: HEAD
      path: observability/argo/values/tempo
      ref: custom
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.21.1
      helm:
        valueFiles:
          - $custom/observability/argo/values/tempo/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
