apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 5.7.0
      helm:
        valueFiles:
          - $custom/patterns/observability/argo/values/mimir.yaml
    - repoURL: https://github.com/henrypham67/istio
      targetRevision: HEAD
      ref: custom
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true