adminPassword: admin
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    # Allow discovery in all namespaces for dashboards
    searchNamespace: ALL

dataSources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        url: http://mimir-nginx.monitoring.svc.cluster.local/prometheus
        isDefault: true
      - uid: tempo
        orgId: 1
        name: Tempo
        type: tempo
        typeName: Tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3100
        password: ''
        user: ''
        database: ''
        basicAuth: false
        isDefault: false
        jsonData:
          nodeGraph:
            enabled: true
          tracesToLogsV2:
            customQuery: false
            datasourceUid: loki
            filterBySpanID: false
            filterByTraceID: true
            tags:
              - key: service.name
                value: compose_service
        readOnly: false
        editable: true
      - uid: loki
        orgId: 1
        name: Loki
        type: loki
        typeName: Loki
        access: proxy
        url: http://loki-gateway.logging.svc.cluster.local
        password: ''
        user: ''
        database: ''
        basicAuth: false
        isDefault: false
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: (?:trace_id)=(\w+)
              matcherType: regex
              name: TraceID
              url: $${__value.raw}
        readOnly: false
        editable: true